variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - test
  - package

.stage_artifacts: &stage_artifacts
  artifacts:
    paths:
      - build/
      - TriBITS/
      - googletest/
      - testframework/
    expire_in: 1 day

mac_clang_testing:
  tags:
    - mac
  script:
    - . ci/mac_clang_test.sh
  artifacts:
    when: always
    paths:
      - "WASP*Darwin.sh"
      - waspConfig_install.cmake
      - build/wasppy/dist/*.whl
      - build/wasppy/wheelhouse/*.whl

.doc_gen:
  tags:
    - pandoc, mac
  script:
    - which git
    - git --version
    - which cmake
    - which python
    - python --version
    - mkdir build
    - cd build
    - cmake -DBUILDNAME="$(uname -s)-DocGen-${CI_BUILD_REF_NAME}" -DCMAKE_BUILD_TYPE=DEBUG -Dwasp_ENABLE_ALL_PACKAGES=ON -Dwasp_ENABLE_SWIG=OFF ..
    - make doc_gen
  artifacts:
    paths:
      - build/WorkbenchAnalysisSequenceProcessor.docx
      - build/WorkbenchAnalysisSequenceProcessor.pdf

linux_gcc_testing:
  tags:
    - linux
    - pbs
  script:
    - ci/linux_gcc_test.sh
  artifacts:
    when: always
    paths:
      - "WASP*Linux.sh"
      - build/wasppy/dist/*.whl
      - build/wasppy/wheelhouse/*.whl
      - waspConfig_install.cmake

linux_gcc_analysis:
  tags:
    - linux
  script:
    - ci/linux_gcc_analysis.sh
  allow_failure: true

windows_shared_vs2022_testing:
  tags:
    - vs2022
  before_script:
    - echo Cleaning up existing submodule directory...
    - git submodule deinit -f --all
    - IF EXIST TriBITS (
        rmdir /S /Q TriBITS
      )
    - git submodule update --init --recursive
  script:
    - .\ci\vs2022_shared_test.bat
  artifacts:
    when: always
    paths:
      - build/wasppy/dist/*.whl
      - build/wasppy/wheelhouse/*.whl

.cpack_artifacts: &cpack_artifacts
  stage: package
  artifacts:
    name: "wasp-${CI_JOB_NAME}-${CI_COMMIT_REF_SLUG}"
    paths:
      - dist/cpack/
    expire_in: 1 week

linux_cpack:
  <<: *cpack_artifacts
  tags:
    - linux
    - pbs
  variables:
    WASP_CPACK_GENERATOR: STGZ
    WASP_CPACK_PLATFORM: Linux-x86_64
    WASP_MINICONDA_INSTALLER_URL: https://code-int.ornl.gov/lefebvre/miniconda/-/raw/main/Miniconda3-py310_24.5.0-0-Linux-x86_64.sh
  script:
    - ci/unix_cpack.sh

mac_cpack:
  <<: *cpack_artifacts
  tags:
    - mac
  variables:
    WASP_CPACK_GENERATOR: productbuild
    WASP_CPACK_PLATFORM: macOS-universal2
    WASP_CPACK_ARCHITECTURES: "arm64;x86_64"
    WASP_MINICONDA_INSTALLER_URL: https://code-int.ornl.gov/lefebvre/miniconda/-/raw/main/Miniconda3-py310_24.5.0-0-MacOSX-arm64.sh
  script:
    - ci/unix_cpack.sh

windows_cpack:
  <<: *cpack_artifacts
  tags:
    - vs2022
  before_script:
    - echo Cleaning up existing submodule directory...
    - git submodule deinit -f --all
    - IF EXIST TriBITS (
        rmdir /S /Q TriBITS
      )
    - git submodule update --init --recursive
  script:
    - .\ci\vs2022_cpack.bat
