#ifndef WASP_MCNPLEXER_H
#define WASP_MCNPLEXER_H

// Flex expects the signature of yylex to be defined in the macro YY_DECL, and
// the C++ parser expects it to be declared. We can factor both as follows.

#ifndef YY_DECL

#define YY_DECL                                          \
    wasp::MCNPParser::token_type wasp::MCNPLexerImpl::lex( \
        wasp::MCNPParser::semantic_type* yylval,          \
        wasp::MCNPParser::location_type* yylloc)
#endif

#ifndef __FLEX_LEXER_H
#define yyFlexLexer MCNPFlexLexer
#include "waspcore/FlexLexer.h"
#undef yyFlexLexer
#endif

#include "MCNPParser.hpp"
#include "mcnp_node.h"

#include "waspcore/decl.h"
namespace wasp
{
/** MCNPLexerImpl is a derived class to add some extra function to the scanner
 * class. Flex itself creates a class named yyFlexLexer, which is renamed using
 * macros to MCNPLexer. However we change the context of the generated
 * yylex() function to be contained within the MCNPLexerImpl class. This is
 * required
 * because the yylex() defined in MCNPLexer has no parameters. */
class WASP_PUBLIC MCNPLexerImpl : public MCNPFlexLexer
{
  public:
    /** Create a new scanner object. The streams arg_yyin and arg_yyout default
     * to cin and cout, but that assignment is only made when initializing in
     * yylex(). */
    MCNPLexerImpl(class AbstractInterpreter& interpreter,
                 std::istream*              arg_yyin  = 0,
                 std::ostream*              arg_yyout = 0);

    /** Required for virtual functions */
    virtual ~MCNPLexerImpl();

    /** This is the main lexing function. It is generated by flex according to
     * the macro declaration YY_DECL above. The generated bison parser then
     * calls this virtual function to fetch new tokens. */
    virtual MCNPParser::token_type lex(MCNPParser::semantic_type* yylval,
                                      MCNPParser::location_type* yylloc);

    /** Enable debug output (via arg_yyout) if compiled into the scanner. */
    void set_debug(bool b);

    /**
     * @brief rewind - rewind the last token (yyless(0))
     */
    void rewind();

    /**
     * @brief Stores the current token into the token pool
     * 
     * @param yylval the semantic information
     * @param type the type to assign the token
     */
    void capture_token(wasp::MCNPParser::semantic_type* yylval, wasp::mcnpi::NODE type);
    /**
     * @brief converts legacy format (1.6-4, or 1.6D-4 to 1.6e-4)
     * 
     * @param yylval where the capture token index will be stored for parser processing
     * @param type the type of the token
     */
    void capture_upconverted_fortran_float_token(wasp::MCNPParser::semantic_type* yylval, wasp::mcnpi::NODE type);
  private:
    class AbstractInterpreter& interpreter;
    std::size_t                file_offset;
    std::size_t                column_limit; // count afterwhich tokens become comments
};

}  // namespace wasp

#endif  // WASP_MCNPLEXER_H
